apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: nginx-ingress-metrics
  namespace: ingress-nginx
spec:
  clusterIP: None
  ports:
  - name: prometheus
    port: 10254
    targetPort: 10254
  selector:
    app.kubernetes.io/name: ingress-nginx
