apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.99.100
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
