apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager-prometheus-discovery
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.99.100
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
