apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ups-exporter
  name: ups-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: ups-exporter
