apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-external
  namespace: monitoring
  labels:
    traffic-type: external
  annotations:
    traefik.frontend.rule.type: PathPrefix
    #traefik.frontend.redirect.regex: ^http://(.*)
    #traefik.frontend.redirect.replacement: https://$1
spec:
  rules:
  - host: grafana.cloud.carlosedp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
